### ISSUE TITLE
Single file EmguCV executable works in .NET 6 preview 2. But not EmguTF...

### ISSUE THREAD

**Issue by JohnTenney** [emgucv/emgutf#61]
The following command builds a MyProj.exe file that runs in .NET 6 preview 2, as long as I exercise EmguCV but NOT EmguTF:

`dotnet publish MyProj.csproj -c Release -f net6.0-windows -r win10-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true`

However, when I try to run TensorFlow code, I get errors like:

**Application Exception The type initializer for 'Emgu.TF.TfInvoke' threw an exception. CodeBase is not supported on assemblies loaded from a single-file bundle. 
   at Emgu.TF.TfInvoke.tfeNewGraph()
   at Emgu.TF.Graph..ctor()
   ..etc...**

So it looks like you addressed this issue in EmguCV but not EmguTF?

**Comment by JohnTenney** [comment]
Just tested it--works great!
